#!/usr/bin/env bash
# Creates a PID file and handles signals

PID_FILE="/run/myscript.pid"

echo $$ > "$PID_FILE"

term_handler() {
  echo "I hate the kill command"
  rm -f "$PID_FILE"
  exit 0
}

int_handler() {
  echo "Y U no love me?!"
}

trap term_handler SIGTERM SIGQUIT
trap int_handler SIGINT

while true
do
  echo "To infinity and beyond"
  sleep 2
done
